CREATE TABLE images (
  id INTEGER PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  author_id INTEGER,

  FOREIGN KEY(author_id) REFERENCES user(id)
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  uname VARCHAR(255) NOT NULL
);

INSERT INTO
  users (id, uname)
VALUES
  (1, "cCumber"),
  (2, "noGutsNoGlory");

INSERT INTO
  images (id, description, body, author_id)
VALUES
  (1, "The Man The Legend", "

                                    .  ..  .. . .....^^^.^^^.^.^.......^..^.^.^........^.^.^^^^^^.^.......^
                                  . .^... .^.. ..!^^^^!!|||6I|!^.. .. ..................^^.^^^^^^^.........
                                .  .^!I|^!!^||I|6II66I6I6OOOQO66IIIO|^.. . ............^..^^!^^^^^^.... ...
                                I|II|I!|!!|IOOQOQO6OOOI666IOOQOO6Q6II6II^. ..  . . .....^.^^^^^..^.... . ..
                             |II||!!|!I66O6OMQOOQQQ6QOQQO6OOOQQOOQOQO6II66|. .  .. .  .....^......... .. ..
                           !6|I^!I66OQ6OQQQQQMQMQQQQQOQMQOQOQOOQQOOQOOIQO6II|.      . . . ..... . ..  . . .
                         ^||66I6OOQQQOOOQQQQQQMMQQOOQQQOMQQQOOOQQQOQQOOOOOOI6I!       . . . . . . . .. . ..
                        6|!6QOOOQQQMQOOQQQQMQQQMQQO6QOQQQQQQQOOQOQQQOOQOOQOQOO6I^          .      . . .  ..
                      .!6I6OO6QQMQMQOOQQQOQQQMQQQQOOOQOQOOQQQQOQOQMQOO66OOO6QQO6I6                      . .
                      .IOOOQOQQQQQQQOOQQQQOQQMQQQ6OO66OOOOQOOOQQOQOOMQOOO6QOOOOO6OI                    .  .
                      .O66QOOQQQOQQQMOQOQQQOQMQOQQ6OO6QOOQO6OOOQQOOQOQQ6QQ6O66IIOOO6
                     .!OOQQOQOOQQOQOQOOQOQOOQOOOQQ6OO6OOO6OOI6QOQQOQQQQOOQQO666666OQI
                     IOQQQQO6OOOOOOQO6QOOO6OOOOOQQ66O|666OI666O6O6OQQOQQOQOQO66OO6OQ6.
                   .6^OOQQO6OOOOQOOOQOO6O66OOO6OOQOI6|6I6I6I6O6I66Q66OQOOQOOQ6OO6O6OQO
                   .6QQQOOOQO66O6OOO6O666O66O6I6OOQO||666666I6I6!6IQ6O6OQQQOOQQO6666OOI.
   .               .QQOOOOOOQO6OOQOQ666OOO6O66I66OI6OI6OI6O6O|6|I|I|66|OOOOQQQOO6OQ6IO6.
                   6OOOO6OO6OQOQQOQO6OOOI6QO6I666OII6O6OOOIQO66|I6|!|||O!QOOOQOOQOO6OOO^.               ..
                   I6O6OOOOQOQOOQOO66OO6OOI666I66I|I6OOOQQQOOO6QO|6|II6|IOOOQOOQOOO66OOI
                 .^6O66O6QQOOQOOOO66OO6OO66II66O6IIO6O6OO6QOQOOQOO666IIOI6O6QOO6O6OO6OO6.
                   O666OOOOOOOOO6QO666OOO6I666O666666OOOOO6O6OOOO66OOOI6QI6QOQOOO66666OO6!.
                  ^|66OO6O6QOO6QOQOOO6O6O66666OII666OOOO6OO66O6OOO6OOOQIQO66OOQO66O6OQO66^.
                  .I6OO666O6OOQQO66OOO6O6I666O666O6OO6QO6O6I66I66O6O6OOQ6QMOOOQO66666OO6I!
                  |O6O66OOQOOQOOO6OO6666I6666666OOOQOOOOQO6IIII6II6666O6QQQOQOOQOO66I|I66I|..
                  O66666QQOQ6OOO6OOOIII6II6O6I6QOOOQOQOOQO66IIIIII6I66O66OOOQQOQOO666IO66OO|!
                .6IOO6QOOOQO6OOOQ6O66I666O6666OQOQQOOQOOOI6I6II666O6II666IO66OQOOOOQQO6IIII6I|
                I66OOQOO6QQO6QO6OQO6OOQOOOO6OOQOO6OOQO6OO66OQOOOOOO6I66O66O66OQ6QOQOOO66O6I66!
               I66OQ6OI6OMOI6O6OO6OO6666OOOO666OII6III6666OOO6II6I6666I6|II||I6OO6OOOQ66IIO6I.
              |I66OOO|IIOQ6|I66IIIIIII||I6QQQOO666||!|||IOOQQQOMQQQOO6I||!|!!|66OOOOOOO66I666^
              IOIOOO6|I6QQII|I||II66QQQQOQOO6O6III|!|!!||II6I66II!!||I66I|!!!|I6IQOO6OQ6OI6I.
              .O6OO66|I6QO6I|||I66II||||II|II6III|!!!^!!||III||!!!!!|!!!|!!^!!II6OOQ666OQ66^
               !OI666I6OQOII|!|!||||!!!!|||||||I|!|!!!!^!!!!!|!!^!!!^!^^^^^!!!|II6OOI66O6I|^
                6I6OOI6OQ6II||||!!!||!|!!||!!||||||!!!!^!!!!!^!!!!^^^!^^^^^!^!|||I666I666!^.
                .6I6|I6QQ6II||!|!!|!!!!!!!!!||!||||!!!^!^!^!!!^!^^!^!^!^!!^!!!!||I66O6II|!
                  |II66OO6I|||!|!!!!|!!!!^!!!||I|!!!!!!!!!|||!^!^^^^!^!!!!^!!!^!!||O6I!!!.
                   !I66OOO6|||!||!|!!!!!!^!!||||!!!!^!^^!^!!I|!!^^^^^^!^!!^!!!^^!!|II|^^^
                    ^II6OOI|!!||||!|!!!!!!!II||||||!||!!!!!!!6I|!!^!^^^^^!^!^^!!!!!!!|^^ !
                    .!|||I|!|!|||!|!!!!!!|I6|6OQOI6IIIII6Q6I||II|!^^!^!^^!^!^!^!!!!^^!!
                      ||I||!||||!||!!!!!|I6||I66I666O66I|II|!!!|6I|^!^!^^!!^^!!^!OI|!!
                      .||||!|||||||!|!|!II|||||I6I66II666I!!|!!!!I6I!^!^^!^^!^!!!O6O.
                       .|||I|||||!|!!||I||||I66OQOQO666OOOOO6II6||6OI|!^^!^!^!!^I6^
                        .|!I|||||!|!||66I66O6OOQQQQO||IOQQOOO6666OO666|!!!^!^!!^
                           .I|||||||6O6OQOOOO6II6II6||II6II6IIOOQ6O6OO||!|!!!|!II.
                           .!!||||I66O6OOQQOOO6O6I6OOO6II!|||||||I66I|!|!|!!|!!6QMOI
                            .^||!I666II6IIII|I|I||||!!|!!|||!||||II6I|!||!||I!!QMQQQOI
                           ..!II||III|IIII||IIIIII6666I6I6I|||!||!|!|||I|||||!!OMMMQQQO
                           .^|IIII||II||I|||I|I|II|I|III|||!|!!|!!!!!|||!||||||QMMMMQQQO!
                          ..!IIIQOI||II|||||I|!||I|!!!!!!!!|!!^^!!!!||!|I|II|||QMMMMQQQOOOI
                          .^|IIQQQ6IIII|||!|||||!|!|!|!!!!!!!!!!!!||III||IIII|IQMMMMMQQOQOOQ6^
                        ..^!IIQQMMM666I66II|||||!|||||!!!||!||||II6666IIIIIII66MMMMQQMQQOQQQOQO.
                       ...!IIQQMMMMQO666OO66IIIII6IIII|6III6II6O6OO6OI66III666MMMMQQQQMQQQQQQQQQOO!
                        .^|IQQQMMMMMQQOOOOOQOO66666O6OO6OOOOOQQO6OOO6666I666OOMMMQQQQQQQQQQMQQQQQQOQO    .
                      ..^!OQQMQMMMMMMQQQOOQQQQOQQQQQQQQQQQQMMQQO666666IO66OOQMMQMQQQQQQQQQQQQMQQQQQQQQ6. .
                       ^6QQQMQMMMMMMMMQQQOQOQQQQQQQMQQQQQQQOOQQO666666666OOOMMQMMQMMQQQMQMQQQMQMQQMQMQMQOOI
                     .OQQQQQMQQMQMMMMMMQQOQOQQQQQQQQQQOOOOOQOOOOO66I6O66OOQMMMMMMMMMMMQMQQQQQQMQQMQQMQMQQMM
                   .IMQQMQQMQQMQMQMMMMMMQQQOQOOQQQQQQOOOOOOOQOOOO6666OOOOQMQMMMMMMMMMMMQQQMQQQQMQMQMQMMQMMM
                  .MQMQQMQMQMQMMMMMMQMMMMQQQOOOOQOQQQQOQQOOQOOOOOOO6OOOOQQMQMMMMMMMMMMMMMQQQQQQMQMQMMMMMQMM
              .|QMQMQQMMQMQQMMMMMMMMMMMMMMMQQ6OOOQOQQQQOOOOOOQOOOO66OOQOQMQMMMMMMMMMMMMMMMQQQQQQMMQMMMMMQMM
          .|OQQQMQMQMQMQMQMQMMMMMMMMMMMMMMMQQO666OOQOQOOOQOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQQQMQMQMQMMMQMMM
      .6OQQMMMMQMMQMQMQMQMQMMMMMMMMMMMMMMMMQQQO66I6OQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMQMMQMMMMMMMM
  6QQQMMMMMMMMMMMMQMQMQMQMQMMMMMMMMMMMMMMMMQQMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMQMMMMMMMMMMM
  MMQ||QMMMMMMMQMMMQMMQMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMMQMQMMMMMMM
  QMMMMMMMMMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMQMQMMMMMM
  MMMMMMMMMMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQQQMMMMMMMM
  MMMMMMMMMMQMMMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQQMMQMMMM
  MMMMMMMMMMMMMMMMMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMMQMMM
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMMQMM
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMQM
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM www.segnalidivita.com)", 1),
  (2, "Rectangle within a rectangle", "
          ________________________
        / _____________________  /|
       / / ___________________/ / |
      / / /| |               / /  |
     / / / | |              / / . |
    / / /| | |             / / /| |
   / / / | | |            / / / | |
  / / /  | | |           / / /| | |
 / /_/___| | |__________/ / / | | |
/________| | |___________/ /  | | |
| _______| | |__________ | |  | | |
| | |    | | |_________| | |__| | |
| | |    | |___________| | |____| |
| | |   / / ___________| | |_  / /
| | |  / / /           | | |/ / /
| | | / / /            | | | / /
| | |/ / /             | | |/ /
| | | / /              | | ' /
| | |/_/_______________| |  /
| |____________________| | /
|________________________|/ ", 2);
